// Package mailtoken owns offer_token issuance and resolution (02-state-machines.md §3.3,
// 88.6.1–88.6.4): tokens are generated by the mail worker right before each send attempt
// (never in the offer-creation transaction), many tokens may point at one offer, only the
// SHA-256 hash is stored, and validity is derived in real time from the offer/activity
// state — the table itself is stateless.
package mailtoken

import (
	"context"
	"errors"
	"strings"

	"gorm.io/gorm"
	"rollin-backend/internal/errs"
	"rollin-backend/internal/model"
	"rollin-backend/internal/token"
)

// Resolved is the outcome of a token lookup before any state decision: everything the
// caller needs to derive effectiveStatus (02 §3.3 four-element test).
type Resolved struct {
	Token          model.OfferToken
	Offer          model.Offer
	ActivityID     uint64
	ActivityStatus string
	ApplicationID  uint64
	CandidateID    uint64
	CandidateName  string
	SuccessMessage string
}

// Service is the offer-token domain API.
type Service interface {
	// IssueForOffer creates one new token row inside the mail worker's send transaction
	// (created_by_task_id keeps the audit trail to the mail task that minted it).
	// Implemented in P1 — it is the complete storage contract of the table.
	IssueForOffer(ctx context.Context, tx *gorm.DB, offerID, createdByTaskID uint64) (raw string, err error)
	// ResolveByToken returns the offer context for a raw token, or TOKEN_INVALID. P5
	// fills the joins with offer/application/candidate/activity state.
	ResolveByToken(ctx context.Context, raw string) (*Resolved, error)
}

type service struct {
	db     *gorm.DB
	tokens *token.Manager
}

// New wires the offer-token service.
func New(db *gorm.DB) Service { return &service{db: db, tokens: token.New()} }

// IssueForOffer is final in P1: 32 random bytes from crypto/rand, SHA-256 stored, raw
// value returned once for the mail body. The unique hash key makes collision (and
// double-insert of the same token) impossible.
func (s *service) IssueForOffer(ctx context.Context, tx *gorm.DB, offerID, createdByTaskID uint64) (string, error) {
	raw, hash, err := s.tokens.Generate("")
	if err != nil {
		return "", err
	}
	taskID := createdByTaskID
	row := model.OfferToken{OfferID: offerID, TokenHash: hash, CreatedByTaskID: &taskID}
	if err := tx.WithContext(ctx).Create(&row).Error; err != nil {
		return "", err
	}
	return raw, nil
}

// ResolveByToken implements the four-element resolution of 02 §3.3: hash hit → offer →
// application → activity. It is a pure read (INV-7: the caller derives effectiveStatus
// from the returned snapshot; nothing here writes). Any missing hop — unknown hash,
// vanished offer/application/activity — is TOKEN_INVALID with the contractual copy, and
// never leaks which part was missing.
func (s *service) ResolveByToken(ctx context.Context, raw string) (*Resolved, error) {
	if strings.TrimSpace(raw) == "" {
		return nil, errs.New(errs.CodeTokenInvalid, "链接无效或已失效")
	}
	var row model.OfferToken
	err := s.db.WithContext(ctx).Where("token_hash = ?", token.Hash(raw)).First(&row).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, errs.New(errs.CodeTokenInvalid, "链接无效或已失效")
	}
	if err != nil {
		return nil, err
	}
	var offer model.Offer
	if err := s.db.WithContext(ctx).First(&offer, row.OfferID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errs.New(errs.CodeTokenInvalid, "链接无效或已失效")
		}
		return nil, err
	}
	var application model.Application
	if err := s.db.WithContext(ctx).First(&application, offer.ApplicationID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errs.New(errs.CodeTokenInvalid, "链接无效或已失效")
		}
		return nil, err
	}
	var activity model.Activity
	if err := s.db.WithContext(ctx).First(&activity, application.ActivityID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errs.New(errs.CodeTokenInvalid, "链接无效或已失效")
		}
		return nil, err
	}
	successMessage := ""
	if activity.OfferSuccessMessage != nil {
		successMessage = *activity.OfferSuccessMessage
	}
	return &Resolved{
		Token:          row,
		Offer:          offer,
		ActivityID:     activity.ID,
		ActivityStatus: activity.Status,
		ApplicationID:  application.ID,
		CandidateID:    application.CandidateID,
		CandidateName:  application.Name,
		SuccessMessage: successMessage,
	}, nil
}
